name: Integration test

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Cancel the job if new commits are pushed
# https://stackoverflow.com/questions/66335225/how-to-cancel-previous-runs-in-the-pr-when-you-push-new-commitsupdate-the-curre
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:  
    strategy:
      fail-fast: false
      matrix:
        python: ["3.10", "3.12"]
        package: ["mudata", "spatialdata", "scirpy", "muon", "scanpy", "squidpy"]

    defaults:
      run:
        shell: bash -el {0}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: scverse/${{ matrix.package }}
  
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install UV
        uses: hynek/setup-cached-uv@v2

      - name: Install AnnData + test dep
        run: |
          uv pip install --compile --system ".[test]" pytest-xdist "llvmlite>=0.43dev0" -v
          uv pip install --compile --system git+https://github.com/scverse/anndata 
      - name: Env list
        run: uv pip freeze

      - name: Run test
        run: pytest -n auto
